#spring:
#  mvc:#    view:#      prefix: "/WEB-INF/views/"
#      suffix: ".jsp"

spring:
  thymeleaf:
    prefix: "classpath:templates/"
    check-template-location: true
    suffix: ".html"
    mode: "HTML5"
    cache: false
---
spring:  jpa:
    generate-ddl: true
    properties:      hibernate:
        dialect: "org.hibernate.dialect.H2Dialect"
        show_sql: true
        format_sql: true
        use_sql_comments: true

logging:  level:    org.hibernate.SQL: debug
    org.hibernate.type: trace
    kr.or.ddit: debug
    org.springframework: debug
           
---
server:  port: 80      